version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      all-updates:
        patterns:
          - "*"

  - package-ecosystem: "composer"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      all-updates:
        patterns:
          - "*"
