name: Check PR Title

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
      - reopened

jobs:
  check-pr-title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR title
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          prefix_case_sensitive: false
          min_length: 2
          max_length: 25
          github_token: ${{ secrets.GITHUB_TOKEN }}
