name: Check PR Title

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize, ready_for_review, reopened]

jobs:
  check-pr-title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
    uses: deepakputhraya/action-pr-title@master
    with:
    regex: '([a-z])+\/([a-z])+'
    prefix_case_sensitive: false 
    min_length: 2
    max_length: 25
   github_token: ${{ secrets.GITHUB_TOKEN }}