name: Check PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
      - reopened

jobs:
  check-pr-title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint PR title
        uses: github-actions-lint/lint-pull-request-title@v1